name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v3

      # Set up Node.js environment
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      # Install dependencies
      - run: npm ci

      # Lint the project
      - run: npm run lint:ci

      # Build the project
      - run: npm run build

      # Run tests
      - run: npm run test:ci

      # Publish to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
